import assert from 'node:assert/strict';
import {setCanvasRatio,validState} from '../dist/core.mjs';
const base={ratio:'1:1',background:'#e9e4db',text:'검사',textColor:'#ffffff',fontSize:64,textX:50,textY:72,design:'quiet',canvasEnabled:true,photoCanvas:false,keepAspect:true,applyPhotoRatio:false,photo:{src:'data:image/png;base64,iVBORw0KGgo=',x:0,y:0,w:600,h:400,sx:0,sy:0,sw:1200,sh:800}};
const tests=[];const test=(name,fn)=>{fn();tests.push({name,result:'PASS'});};
test('사진에 적용 해제: 사진 크기·자르기 보존',()=>{const s=structuredClone(base);setCanvasRatio(s,'9:16');assert.deepEqual(s.photo,base.photo);assert.equal(s.ratio,'9:16');});
test('체크 후 자르기, 해제 후 변경해도 적용 결과 유지',()=>{const s=structuredClone(base);s.applyPhotoRatio=true;setCanvasRatio(s,'1:1');assert.equal(s.photo.w,400);const edited=structuredClone(s.photo);s.applyPhotoRatio=false;setCanvasRatio(s,'4:5');assert.deepEqual(s.photo,edited);});
test('사진 캔버스가 아니어도 적용 체크 시 크기 변경',()=>{const s=structuredClone(base);s.applyPhotoRatio=true;s.keepAspect=false;setCanvasRatio(s,'4:5');assert.equal(s.photo.w,1080);assert.equal(s.photo.h,1350);});
test('삭제한 캔버스가 비율 클릭으로 나타나지 않음',()=>{for(const apply of [true,false]){const s=structuredClone(base);s.canvasEnabled=false;s.applyPhotoRatio=apply;setCanvasRatio(s,'4:5');assert.equal(s.canvasEnabled,false);}});
test('새 플래그 JSON 검증',()=>{assert.equal(validState(base),true);assert.equal(validState({...base,applyPhotoRatio:'yes'}),false);});
console.log(JSON.stringify({scope:'Node state tests, not browser QA',tests},null,2));
