import assert from 'node:assert/strict';
import {setCanvasRatio,canvasDimensions,outputRect,sceneRect,checkedExportSize,cropRect,resizeRect,validState,validateBundle} from '../dist/core.mjs';
const base={ratio:'1:1',background:'#e9e4db',text:'검사',textColor:'#ffffff',fontSize:64,textX:50,textY:50,design:'quiet',canvasEnabled:true,photoCanvas:false,keepAspect:false,photo:{src:'data:image/png;base64,iVBORw0KGgo=',x:0,y:0,w:600,h:400,sx:0,sy:0,sw:1200,sh:800}};
const rows=[];function test(name,fn){try{fn();rows.push({name,result:'PASS'});}catch(e){rows.push({name,result:'FAIL',error:e.message});process.exitCode=1;}}
for(const [ratio,h] of [['1:1',1080],['4:5',1350],['9:16',1920]])for(const pos of [{x:0,y:0},{x:-700,y:120},{x:2400,y:2500}])test(`${ratio} canvas / photo at ${pos.x},${pos.y}`,()=>{const s=structuredClone(base);Object.assign(s.photo,pos);const before=structuredClone(s.photo);setCanvasRatio(s,ratio);assert.deepEqual(canvasDimensions(s),[1080,h]);assert.deepEqual(s.photo,before);assert.deepEqual(outputRect(s),{x:0,y:0,w:1080,h});const bounds=sceneRect(s);assert.ok(bounds.x<=pos.x&&bounds.y<=pos.y&&bounds.x+bounds.w>=pos.x+600);});
for(const old of [true,false])test('Legacy applyPhotoRatio '+old+' cannot block linked canvas ratio',()=>{const s=structuredClone(base);s.photoCanvas=true;s.applyPhotoRatio=old;setCanvasRatio(s,'9:16');assert.deepEqual(canvasDimensions(s),[1080,1920]);assert.equal(s.photo.x,0);});
test('Free photo crop preserves scale and centered source',()=>{const s=structuredClone(base);s.canvasEnabled=false;s.keepAspect=true;s.photo.x=-1300;setCanvasRatio(s,'1:1');assert.equal(s.photo.w,400);assert.equal(s.photo.w/s.photo.sw,.5);assert.equal(s.photo.x,-1200);assert.equal(s.photo.sx,200);assert.equal(s.canvasEnabled,false);});
test('Free photo stretch keeps center after move',()=>{const s=structuredClone(base);s.canvasEnabled=false;s.photo.x=2500;const center=s.photo.x+s.photo.w/2;setCanvasRatio(s,'4:5');assert.equal(s.photo.x+s.photo.w/2,center);assert.deepEqual(canvasDimensions(s),[1080,1350]);});
test('Linked photo center crop updates canvas ratio',()=>{const s=structuredClone(base);s.photoCanvas=true;s.keepAspect=true;setCanvasRatio(s,'4:5');assert.deepEqual(canvasDimensions(s),[320,400]);assert.equal(s.photo.x,0);assert.equal(s.photo.y,0);});
test('Moved photo crop stays within source bounds',()=>{const p={x:-500,y:300,w:600,h:400};const r=cropRect(p,'nw',100,80,p);assert.deepEqual(r,{x:-400,y:380,w:500,h:320});});
test('Side resize retains other dimension past 10000px',()=>{const p=resizeRect(base.photo,'e',20000,0,true);assert.equal(p.w,20600);assert.equal(p.h,400);});
test('Undo snapshot restores exact crop/position/ratio',()=>{const s=structuredClone(base);s.photoCanvas=true;s.keepAspect=true;const prior=structuredClone(s);setCanvasRatio(s,'9:16');Object.assign(s,structuredClone(prior));assert.deepEqual(s,prior);});
test('No bitmap allocation requested for oversized export',()=>{assert.throws(()=>checkedExportSize(10000,10000));assert.throws(()=>checkedExportSize(Infinity,1080));assert.deepEqual(checkedExportSize(1080,1920),[1080,1920]);});
test('Old JSON fields remain import-compatible',()=>{const s=structuredClone(base);s.applyPhotoRatio=false;assert.equal(validState(s),true);assert.equal(validateBundle({version:1,templates:[{id:'a',name:'old',state:s}]}).length,1);});
console.log(JSON.stringify({scope:'Node state and geometry regressions; not browser QA',tests:rows},null,2));
