import test from 'node:test';import assert from 'node:assert/strict';
import {session,sessionCookie,prepareUpload,commitUpload,getCollection,MAX_BYTES} from '../server/service.mjs';
import {saveRemote,loadRemote} from '../public/storage.mjs';
import {DEFAULT,parseTemplates} from '../public/engine.mjs';
const secret='test-only-secret-not-for-deployment-0123456789';
const owner='a'.repeat(64);
const template=(id='one')=>({id,name:id,state:{...DEFAULT}});
function fakeStore(){const rows=new Map(),files=new Map();return {rows,files,
 async read(id){return rows.get(id)||null;},async signedUpload(p){return 'https://storage.test/upload/'+p;},async signedRead(p){return 'https://storage.test/read/'+p;},
 async download(p){if(!files.has(p))throw Error('missing file');return new Blob([files.get(p)]);},async upload(p,s){if(files.has(p))throw Error('exists');files.set(p,s);},async remove(p){files.delete(p);},
 async commit(id,rev,key){const row=rows.get(id);if((row?.revision||0)!==rev)return {conflict:true};rows.set(id,{object_key:key,revision:rev+1});return {revision:rev+1,previous_key:row?.object_key};}
};}
async function stage(store,items,revision=0){const payload=JSON.stringify({version:1,templates:items});const p=await prepareUpload(store,owner,{revision,bytes:Buffer.byteLength(payload)},secret);store.files.set(p.path,payload);return p;}
test('새 쿠키와 기존 쿠키, 변조 쿠키를 구분한다',()=>{const a=session('',secret);assert(a.fresh);const cookie=sessionCookie(a,secret,true);assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.deepEqual(session(cookie,secret),{owner:a.owner,fresh:false});assert(session(cookie.replace(a.owner,'b'.repeat(64)),secret).fresh);});
test('3개 생성, 수정, 삭제, 다시 불러오기',async()=>{const s=fakeStore();let p=await stage(s,[template('one'),template('two'),template('three')]);assert.equal((await commitUpload(s,owner,p,secret)).revision,1);p=await stage(s,[{...template('one'),name:'수정됨'},template('two')],1);await commitUpload(s,owner,p,secret);const row=await s.read(owner);const data=JSON.parse(s.files.get(row.object_key));assert.equal(data.templates.length,2);assert.equal(data.templates[0].name,'수정됨');assert.equal((await getCollection(s,owner)).revision,2);});
test('손상 JSON 뒤에는 기존 목록이 유지된다',async()=>{const s=fakeStore();await commitUpload(s,owner,await stage(s,[template()]),secret);const before=await s.read(owner);const p=await stage(s,[],1);s.files.set(p.path,'{');await assert.rejects(commitUpload(s,owner,p,secret),/문법/);assert.deepEqual(await s.read(owner),before);assert(s.files.has(before.object_key));});
test('필수 항목 누락 JSON은 저장 전에 거부한다',async()=>{const s=fakeStore();const p=await stage(s,[]);s.files.set(p.path,JSON.stringify({version:1,templates:[{id:'a',name:'a',state:{text:'누락'}}]}));await assert.rejects(commitUpload(s,owner,p,secret),/필수/);assert.equal(await s.read(owner),null);});
test('다른 소유자의 업로드 완료 요청을 거부한다',async()=>{const s=fakeStore(),p=await stage(s,[template()]);await assert.rejects(commitUpload(s,'b'.repeat(64),p,secret),/올바르지/);assert.equal(s.rows.size,0);});
test('만료되거나 변경된 저장 티켓을 거부한다',async()=>{const s=fakeStore(),p=await stage(s,[]);await assert.rejects(commitUpload(s,owner,{...p,expires:1},secret));await assert.rejects(commitUpload(s,owner,{...p,revision:1},secret));});
test('다른 창에서 수정한 이전 버전은 덮어쓰지 않는다',async()=>{const s=fakeStore();const first=await stage(s,[template('first')]);const stale=await stage(s,[template('stale')]);await commitUpload(s,owner,first,secret);await assert.rejects(commitUpload(s,owner,stale,secret),e=>e.status===409);assert.match(s.files.get((await s.read(owner)).object_key),/first/);});
test('응답 유실 후 같은 티켓 재시도는 중복 저장하지 않는다',async()=>{const s=fakeStore(),p=await stage(s,[template()]);await commitUpload(s,owner,p,secret);assert.equal((await commitUpload(s,owner,p,secret)).revision,1);});
test('업로드 URL을 다시 사용해도 완료된 파일은 바뀌지 않는다',async()=>{const s=fakeStore(),p=await stage(s,[template()]);await commitUpload(s,owner,p,secret);s.files.set(p.path,'malicious replacement');assert.equal(JSON.parse(s.files.get((await s.read(owner)).object_key)).templates[0].id,'one');});
test('크기와 저장 버전의 극단 입력을 거부한다',async()=>{const s=fakeStore();await assert.rejects(prepareUpload(s,owner,{revision:0,bytes:MAX_BYTES+1},secret),e=>e.status===413);await assert.rejects(prepareUpload(s,owner,{revision:-1,bytes:1},secret),e=>e.status===400);});
test('저장소 오류 시 기존 목록이 유지된다',async()=>{const s=fakeStore();await commitUpload(s,owner,await stage(s,[template()]),secret);const old=await s.read(owner),p=await stage(s,[template('new')],1);s.upload=async()=>{throw Error('storage down');};await assert.rejects(commitUpload(s,owner,p,secret));assert.deepEqual(await s.read(owner),old);});
test('큰 이미지 본문은 Vercel API가 아닌 서명 URL로 전송한다',async()=>{const requests=[];const fetcher=async(url,options={})=>{requests.push({url,...options});if(url==='/api/templates'){const body=JSON.parse(options.body);return Response.json(body.action==='prepare'?{uploadUrl:'https://storage.test/upload',path:'p',expires:99,ticket:'t'}:{revision:1});}return new Response('{}');};const result=await saveRemote([template()],0,fetcher);assert.equal(result.revision,1);assert.equal(requests[1].method,'PUT');assert(requests[1].body instanceof Blob);assert(requests.filter(x=>x.url==='/api/templates').every(x=>x.body.length<8192));});
test('읽기도 Storage에서 직접 복원하고 서버 revision을 유지한다',async()=>{const f=async url=>url==='/api/templates'?Response.json({revision:8,downloadUrl:'https://storage.test/read'}):Response.json({version:1,templates:[template()]});const result=await loadRemote(f);assert.equal(result.revision,8);assert.equal(parseTemplates(JSON.stringify(result)).length,1);});
test('직접 업로드 실패 시 commit을 호출하지 않는다',async()=>{let commits=0;const f=async(url,options)=>{if(url==='/api/templates'){const b=JSON.parse(options.body);if(b.action==='commit')commits++;return Response.json({uploadUrl:'https://storage.test/upload'});}return new Response('',{status:500});};await assert.rejects(saveRemote([],0,f));assert.equal(commits,0);});
test('파일 저장 후 DB 요청이 유실되어도 동일 티켓으로 복구한다',async()=>{const s=fakeStore(),p=await stage(s,[template()]);const commit=s.commit;s.commit=async()=>{throw Error('network interrupted');};await assert.rejects(commitUpload(s,owner,p,secret));s.commit=commit;assert.equal((await commitUpload(s,owner,p,secret)).revision,1);});
